### ISSUE TITLE
Add parameter to decrease AMCL's laser confidence

### ISSUE THREAD

**Issue by dimaxano** [cmrobotics/navigation2#22]
One should have a chance to change param value on the fly and apply that change. Either via separate service or parameter_server

**Comment by artemiialessandrini** [comment]
Shall we introduce dynamic reconfiguring for AMCL? It's been stable in ROS2 for some time

**Comment by dimaxano** [comment]
Seems like one of the options
Do you maybe have some examples of ROS2 packages where it is implemented?

**Comment by artemiialessandrini** [comment]
https://github.com/ros-planning/navigation2/pull/2932

**Comment by artemiialessandrini** [comment]
We have this PR :)
It looks cherry-pickable
I've been thinking about dynamically changing the laser model weights 
If it won't work, dynamic reconfiguring will be useful for calibration

**Comment by dimaxano** [comment]
Very nice! I'll check it, but I have concern that it restarts everything. How robot will behave if we change params during the movement?

**Comment by artemiialessandrini** [comment]
The concept is to dynamically change parameters without unexpected behaviors, crashes or restarts.
Maybe there're some parameters we shouldn't tweak during the run just by definition.
But other than that it's ok :)

**Comment by dimaxano** [comment]
#26 
#27
